on:
  workflow_dispatch:
  # schedule:
  #   - cron: "* */4 * * *"

name: Update a pinned gist with your Netflix viewing history

jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update gist
        uses: ./
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIST_ID: 8d945773bc8a9980eb63d463eeb10a59
          NETFLIX_EMAIL: ${{ secrets.NETFLIX_EMAIL }}
          NETFLIX_PASSWORD: ${{ secrets.NETFLIX_PASSWORD }}
          NETFLIX_GUID: ${{ secrets.NETFLIX_GUID }}
