on:
  schedules:
    - cron: "*/10 * * * *"

name: Update gist with latest tweet

jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: update-gist
        uses: matchai/bird-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 8d945773bc8a9980eb63d463eeb10a59
          NETFLIX_EMAIL: ${{ secrets.NETFLIX_EMAIL }}
          NETFLIX_PASSWORD: ${{ secrets.NETFLIX_PASSWORD }}
